// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskBoad.Infrastructure.Persistencia;

#nullable disable

namespace TaskBoad.Infrastructure.Persistencia.Migracoes
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923151548_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskBoad.Domain.Entidades.AreaDeTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("DonoId")
                        .HasColumnType("uuid")
                        .HasColumnName("dono_id");

                    b.Property<bool>("EhPessoal")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_pessoal");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_areas_de_trabalho");

                    b.HasIndex("DonoId")
                        .HasDatabaseName("ix_areas_de_trabalho_dono_id");

                    b.ToTable("areas_de_trabalho", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("CartaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cartao_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Dados")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados");

                    b.Property<Guid>("QuadroId")
                        .HasColumnType("uuid")
                        .HasColumnName("quadro_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_atividades");

                    b.HasIndex("CartaoId")
                        .HasDatabaseName("ix_atividades_cartao_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_atividades_usuario_id");

                    b.HasIndex("QuadroId", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_atividades_quadro_id_criado_em");

                    b.ToTable("atividades", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Cartao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("boolean")
                        .HasColumnName("arquivado");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluido_em");

                    b.Property<string>("CorDaCapa")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor_da_capa");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("ListaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lista_id");

                    b.Property<double>("Posicao")
                        .HasColumnType("double precision")
                        .HasColumnName("posicao");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cartoes");

                    b.HasIndex("CriadoPorId")
                        .HasDatabaseName("ix_cartoes_criado_por_id");

                    b.HasIndex("ListaId", "Posicao")
                        .HasDatabaseName("ix_cartoes_lista_id_posicao");

                    b.ToTable("cartoes", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.CartaoEtiqueta", b =>
                {
                    b.Property<Guid>("CartaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cartao_id");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etiqueta_id");

                    b.HasKey("CartaoId", "EtiquetaId")
                        .HasName("pk_cartao_etiquetas");

                    b.HasIndex("EtiquetaId")
                        .HasDatabaseName("ix_cartao_etiquetas_etiqueta_id");

                    b.ToTable("cartao_etiquetas", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.CartaoResponsavel", b =>
                {
                    b.Property<Guid>("CartaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cartao_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("CartaoId", "UsuarioId")
                        .HasName("pk_cartao_responsaveis");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_cartao_responsaveis_usuario_id");

                    b.ToTable("cartao_responsaveis", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cartao_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<double>("Posicao")
                        .HasColumnType("double precision")
                        .HasColumnName("posicao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_checklists");

                    b.HasIndex("CartaoId")
                        .HasDatabaseName("ix_checklists_cartao_id");

                    b.ToTable("checklists", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cartao_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("editado_em");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_comentarios");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("ix_comentarios_autor_id");

                    b.HasIndex("CartaoId", "CriadoEm")
                        .HasDatabaseName("ix_comentarios_cartao_id_criado_em");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<Guid>("QuadroId")
                        .HasColumnType("uuid")
                        .HasColumnName("quadro_id");

                    b.HasKey("Id")
                        .HasName("pk_etiquetas");

                    b.HasIndex("QuadroId")
                        .HasDatabaseName("ix_etiquetas_quadro_id");

                    b.ToTable("etiquetas", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.ItemChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_id");

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean")
                        .HasColumnName("concluido");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<double>("Posicao")
                        .HasColumnType("double precision")
                        .HasColumnName("posicao");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_itens_checklist");

                    b.HasIndex("ChecklistId")
                        .HasDatabaseName("ix_itens_checklist_checklist_id");

                    b.ToTable("itens_checklist", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Lista", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Arquivada")
                        .HasColumnType("boolean")
                        .HasColumnName("arquivada");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<double>("Posicao")
                        .HasColumnType("double precision")
                        .HasColumnName("posicao");

                    b.Property<Guid>("QuadroId")
                        .HasColumnType("uuid")
                        .HasColumnName("quadro_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_listas");

                    b.HasIndex("QuadroId", "Posicao")
                        .HasDatabaseName("ix_listas_quadro_id_posicao");

                    b.ToTable("listas", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.MembroAreaDeTrabalho", b =>
                {
                    b.Property<Guid>("AreaDeTrabalhoId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_de_trabalho_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("EntrouEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrou_em");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("papel");

                    b.HasKey("AreaDeTrabalhoId", "UsuarioId")
                        .HasName("pk_membros_area_de_trabalho");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_membros_area_de_trabalho_usuario_id");

                    b.ToTable("membros_area_de_trabalho", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("idioma");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfis");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_email");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Quadro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaDeTrabalhoId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_de_trabalho_id");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("boolean")
                        .HasColumnName("arquivado");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CorDeFundo")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor_de_fundo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_quadros");

                    b.HasIndex("AreaDeTrabalhoId")
                        .HasDatabaseName("ix_quadros_area_de_trabalho_id");

                    b.HasIndex("CriadoPorId")
                        .HasDatabaseName("ix_quadros_criado_por_id");

                    b.ToTable("quadros", (string)null);
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.AreaDeTrabalho", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Perfil", null)
                        .WithMany()
                        .HasForeignKey("DonoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_areas_de_trabalho_perfis_dono_id");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Atividade", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Cartao", null)
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_atividades_cartoes_cartao_id");

                    b.HasOne("TaskBoad.Domain.Entidades.Quadro", null)
                        .WithMany()
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_atividades_quadros_quadro_id");

                    b.HasOne("TaskBoad.Domain.Entidades.Perfil", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atividades_perfis_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Cartao", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Perfil", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cartoes_perfis_criado_por_id");

                    b.HasOne("TaskBoad.Domain.Entidades.Lista", "Lista")
                        .WithMany("Cartoes")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartoes_listas_lista_id");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.CartaoEtiqueta", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Cartao", null)
                        .WithMany("Etiquetas")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartao_etiquetas_cartoes_cartao_id");

                    b.HasOne("TaskBoad.Domain.Entidades.Etiqueta", "Etiqueta")
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartao_etiquetas_etiquetas_etiqueta_id");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.CartaoResponsavel", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Cartao", null)
                        .WithMany("Responsaveis")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartao_responsaveis_cartoes_cartao_id");

                    b.HasOne("TaskBoad.Domain.Entidades.Perfil", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartao_responsaveis_perfis_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Checklist", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Cartao", null)
                        .WithMany("Checklists")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklists_cartoes_cartao_id");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Comentario", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Perfil", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comentarios_perfis_autor_id");

                    b.HasOne("TaskBoad.Domain.Entidades.Cartao", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comentarios_cartoes_cartao_id");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Etiqueta", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Quadro", null)
                        .WithMany("Etiquetas")
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etiquetas_quadros_quadro_id");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.ItemChecklist", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Checklist", null)
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_checklist_checklists_checklist_id");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Lista", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.Quadro", "Quadro")
                        .WithMany("Listas")
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listas_quadros_quadro_id");

                    b.Navigation("Quadro");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.MembroAreaDeTrabalho", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.AreaDeTrabalho", null)
                        .WithMany("Membros")
                        .HasForeignKey("AreaDeTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_area_de_trabalho_areas_de_trabalho_area_de_trabalho~");

                    b.HasOne("TaskBoad.Domain.Entidades.Perfil", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_area_de_trabalho_perfis_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Quadro", b =>
                {
                    b.HasOne("TaskBoad.Domain.Entidades.AreaDeTrabalho", "AreaDeTrabalho")
                        .WithMany("Quadros")
                        .HasForeignKey("AreaDeTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quadros_areas_de_trabalho_area_de_trabalho_id");

                    b.HasOne("TaskBoad.Domain.Entidades.Perfil", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quadros_perfis_criado_por_id");

                    b.Navigation("AreaDeTrabalho");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.AreaDeTrabalho", b =>
                {
                    b.Navigation("Membros");

                    b.Navigation("Quadros");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Cartao", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Comentarios");

                    b.Navigation("Etiquetas");

                    b.Navigation("Responsaveis");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Checklist", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Lista", b =>
                {
                    b.Navigation("Cartoes");
                });

            modelBuilder.Entity("TaskBoad.Domain.Entidades.Quadro", b =>
                {
                    b.Navigation("Etiquetas");

                    b.Navigation("Listas");
                });
#pragma warning restore 612, 618
        }
    }
}
